package keymap

// Defaults are agtop's own keys, as its key handling is written. Keys that
// only edit text (arrows in a box, ctrl+a, backspace) aren't here: they
// belong to the box, not to an action.
var Defaults = []Action{
	{ID: "bar.open", Context: Global, Title: "the command bar", Keys: []string{"ctrl+k", "super+k"}},
	{ID: "bar.scope", Context: Global, Title: "the command bar, next scope", Keys: []string{"ctrl+f"}},
	{ID: "quit", Context: Global, Title: "quit agtop", Keys: []string{"ctrl+q"}},
	{ID: "zen", Context: Global, Title: "Zen on and off", Keys: []string{"ctrl+z"}},
	{ID: "place.prev", Context: Global, Title: "the place before", Keys: []string{",", "<"}},
	{ID: "place.next", Context: Global, Title: "the next place", Keys: []string{".", ">", "ctrl+\\"}},
	{ID: "profile.pick", Context: Global, Title: "switch the default profile or provider", Keys: []string{"alt+w"}},

	{ID: "list.up", Context: List, Title: "the agent above", Keys: []string{"up"}},
	{ID: "list.down", Context: List, Title: "the agent below", Keys: []string{"down"}},
	{ID: "list.pageup", Context: List, Title: "ten agents up", Keys: []string{"pgup"}},
	{ID: "list.pagedown", Context: List, Title: "ten agents down", Keys: []string{"pgdown", "ctrl+d"}},
	{ID: "list.first", Context: List, Title: "the first agent", Keys: []string{"home"}},
	{ID: "list.last", Context: List, Title: "the last agent", Keys: []string{"end"}},
	{ID: "list.enter", Context: List, Title: "open or rename the agent, or send what's typed", Keys: []string{"enter"}},
	{ID: "list.open", Context: List, Title: "open the agent's Session", Keys: []string{"ctrl+o"}},
	{ID: "list.right", Context: List, Title: "into the agent, or unfold a heading", Keys: []string{"right"}},
	{ID: "list.left", Context: List, Title: "fold the heading", Keys: []string{"left"}},
	{ID: "list.back", Context: List, Title: "clear, go back, or (twice) quit", Keys: []string{"esc"}},
	{ID: "list.rename", Context: List, Title: "rename the agent", Keys: []string{"ctrl+r"}},
	{ID: "list.draft.save", Context: List, Title: "keep what's typed as a draft", Keys: []string{"alt+s"}},
	{ID: "list.draft.recall", Context: List, Title: "bring back a draft", Keys: []string{"alt+p"}},
	{ID: "list.folder", Context: List, Title: "choose the folder, or move the agent", Keys: []string{"ctrl+l"}},
	{ID: "list.pr", Context: List, Title: "open the agent's pull request", Keys: []string{"ctrl+y"}},
	{ID: "list.pin", Context: List, Title: "pin the agent", Keys: []string{"ctrl+t"}},
	{ID: "list.groupby", Context: List, Title: "group agents by the next", Keys: []string{"ctrl+s"}},
	{ID: "list.split", Context: List, Title: "split each section by project, or stop", Keys: []string{"ctrl+p"}},
	{ID: "list.stop", Context: List, Title: "stop or remove the agent", Keys: []string{"ctrl+x"}},
	{ID: "list.done", Context: List, Title: "move the agent to Done", Keys: []string{"alt+d"}},
	{ID: "list.go", Context: List, Title: "tell the agent to keep going", Keys: []string{"alt+g"}},
	{ID: "list.dock.more", Context: List, Title: "a taller card under the list", Keys: []string{"shift+up"}},
	{ID: "list.dock.less", Context: List, Title: "a shorter card under the list", Keys: []string{"shift+down"}},
	{ID: "list.view.prev", Context: List, Title: "the agent's view before", Keys: []string{"["}},
	{ID: "list.view.next", Context: List, Title: "the agent's next view", Keys: []string{"]"}},
	{ID: "list.needs", Context: List, Title: "the next agent that needs you", Keys: []string{"ctrl+n"}},
	{ID: "list.split.less", Context: List, Title: "less of the screen for the list", Keys: []string{"shift+left", "alt+left"}},
	{ID: "list.split.more", Context: List, Title: "more of the screen for the list", Keys: []string{"shift+right", "alt+right"}},
	{ID: "list.help", Context: List, Title: "the keys, with nothing typed", Keys: []string{"?"}},
	{ID: "list.editor", Context: List, Title: "write what's typed in your editor", Keys: []string{"ctrl+g"}},
	{ID: "list.image", Context: List, Title: "paste an image", Keys: []string{"ctrl+v"}},
	{ID: "list.focus", Context: List, Title: "into the Session, and back", Keys: []string{"tab"}},

	{ID: "session.send", Context: Session, Title: "send now, the queue first", Keys: []string{"ctrl+s"}},
	{ID: "session.enter", Context: Session, Title: "send, or open what's picked", Keys: []string{"enter"}},
	{ID: "session.right", Context: Session, Title: "open what's picked", Keys: []string{"right"}},
	{ID: "session.back", Context: Session, Title: "back: off a row, out of a subagent, to Agents", Keys: []string{"left"}},
	{ID: "session.esc", Context: Session, Title: "clear, drop the selection, or leave", Keys: []string{"esc"}},
	{ID: "session.up", Context: Session, Title: "the row above", Keys: []string{"up"}},
	{ID: "session.down", Context: Session, Title: "the row below", Keys: []string{"down"}},
	{ID: "session.pageup", Context: Session, Title: "scroll up", Keys: []string{"pgup"}},
	{ID: "session.pagedown", Context: Session, Title: "scroll down", Keys: []string{"pgdown"}},
	{ID: "session.bottom", Context: Session, Title: "back to the latest", Keys: []string{"end"}},
	{ID: "session.toggle", Context: Session, Title: "open or close the row", Keys: []string{"space"}},
	{ID: "session.drafts", Context: Session, Title: "drafts, sent and cleared", Keys: []string{"ctrl+r"}},
	{ID: "session.draft.save", Context: Session, Title: "keep what's typed as a draft", Keys: []string{"alt+s"}},
	{ID: "session.draft.recall", Context: Session, Title: "bring back a draft", Keys: []string{"alt+p"}},
	{ID: "session.done", Context: Session, Title: "move the agent to Done", Keys: []string{"alt+d"}},
	{ID: "session.hold", Context: Session, Title: "hold or release the queue", Keys: []string{"alt+h"}},
	{ID: "session.rewind", Context: Session, Title: "rewind to the turn, or mark a file reviewed", Keys: []string{"alt+r"}},
	{ID: "session.fork", Context: Session, Title: "fork from the turn", Keys: []string{"alt+f"}},
	{ID: "session.copy", Context: Session, Title: "copy the answer or drawing", Keys: []string{"alt+c"}},
	{ID: "session.sub.next", Context: Session, Title: "the next subagent run", Keys: []string{"alt+down"}},
	{ID: "session.sub.prev", Context: Session, Title: "the subagent run before", Keys: []string{"alt+up"}},
	{ID: "session.view.prev", Context: Session, Title: "the view before", Keys: []string{"["}},
	{ID: "session.view.next", Context: Session, Title: "the next view", Keys: []string{"]"}},
	{ID: "session.verbose", Context: Session, Title: "more or less detail", Keys: []string{"ctrl+o"}},
	{ID: "session.stop", Context: Session, Title: "stop the turn, then the session", Keys: []string{"ctrl+x"}},
	{ID: "session.background", Context: Session, Title: "background what the turn waits on", Keys: []string{"ctrl+b"}},
	{ID: "session.mode", Context: Session, Title: "the next permission mode", Keys: []string{"shift+tab"}},
	{ID: "session.needs", Context: Session, Title: "the next agent that needs you", Keys: []string{"ctrl+n"}},
	{ID: "session.split.less", Context: Session, Title: "less of the screen for the list", Keys: []string{"shift+left", "alt+left"}},
	{ID: "session.split.more", Context: Session, Title: "more of the screen for the list", Keys: []string{"shift+right", "alt+right"}},
	{ID: "session.editor", Context: Session, Title: "write what's typed in your editor", Keys: []string{"ctrl+g"}},
	{ID: "session.image", Context: Session, Title: "paste an image", Keys: []string{"ctrl+v"}},
	{ID: "session.focus", Context: Session, Title: "back to Agents, and in again", Keys: []string{"tab"}},
}

// CommandID is the action that runs a # command.
func CommandID(name string) string { return "command:" + name }

// PluginID is the action that runs a plugin's command.
func PluginID(plugin, command string) string { return "plugin:" + plugin + "." + command }
